- server/main.lua
Changed the "." to a "," to have the correct notification of not enough money
> Changed thousands seperator for money notification

- README.md
- client.lua
- config.lua
First time using LUA, Be gentle😆
> Added support for shops outside of the two default ones

- client.lua
This add an extra config option for you to either show or hide the blips
> Add configurable showBlip

- client.lua
- Refered to global state for inside shop instead of local
Fixes #88 #87 #92 
The `ClosestShop` variable was redundant as its value could be derived from `InsideZones` therefore I have removed it as it was adding complexity to the global space of the resouce, and was causing some issue mainting its value.
The issue was that the value of ClosestShop was used at the local level inside of the functions, instead of reffering back to the global state. Therefore I have removed the ClosestShop value and instead have created a method to retrieve the ClosestShop to replace the variable ClosestShop.
This seems to of removed the issue with the script thinking users are still in PMD or Luxury when they are not.
> Fixed resource thinking user is in wrong shop

- client.lua
- server.lua
This pull request replaces the closest player to a selected player id. This was tested but not on a production build just made sure it worked didnt really go too in depth.
> feat(ManagedShops): Player ID instead of Closest Player

- config.lua
Coords for MLO | -1258.97 -345.35 36.87
> Config Changes to support new Luxury MLO

- README.md
Updated instructions and link for creating new zones a lot of players have been asking.
> PolyZone Wiki Direct page

- client.lua
> Financed Veh typo

- client.lua
- config.lua
Change the blip sprites/colors of shops instead of having one blip for all.
> Configurable Blips Sprites/Colors

- client.lua
- config.lua
Little placement corrections
New shop for air vehicles at airport
Return of the boat shop at marina
> Boat and air shops

- client.lua
- server.lua
Fixes #156
This isn't tested due to me not being available to test it but only to write the fix
> Fix transfervehicle exploits and duplicate polyzone issues

- client.lua
Icons update to support newest qb-menu changes.
Vehicle Menu: 
https://gyazo.com/4bf7cf2f53a6f3c686d64d343e5d7719
Finance Menu:
https://gyazo.com/241260eaba6573c832fc91b4aaa821ee
https://gyazo.com/456b4d2e1bb0845a11a8e1eef594a7ab
> Icons update

- .github/workflows/lint.yml
- client.lua
- server.lua
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]
> Fix linting issues

- server.lua
Defaults the garage to 'pillboxgarage' garage when purchasing a vehicle otherwise the garage will remain NULL unless the player puts there vehicle in a garage before exiting or server restart.
> Default Garage

- config.lua
This pr will fix test drive vehicle spawn location.
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]
> Test drive location error

- client.lua
I was flying around just testing stuff and I noticed that I was able to buy a vehicle from 200 meters up in the sky 🤣  which I  thought was kind of funny and decided to do a hotfix for it
Before
This is after adding the changes
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit …
> PolyZones  going to the heavens (Fix)

- client.lua
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality?  [yes] 
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]
> finance zone max Z

- config.lua
the minimum and maximum z value for the planes vehicleshop is so underneat the ground.
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? yes
- Does your code fit the style guidelines? yes
- Does your PR fit the contribution guidelines? yes
> Fixed minZ and maxZ for the planes shop

- server.lua
> tonumber check on vehiclePrice

- server.lua
Transfervehicle command will cause a trancate error on the AND state, it needs to be a, when you want to update multiple colums
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? yes
- Does your code fit the style guidelines? yes
- Does your PR fit the contribution guidelines? yes
> Transfervehicle command issue

- server.lua
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? no
- Does your code fit the style guidelines? yes
- Does your PR fit the contribution guidelines? yes
> missing locale

- client.lua
Temp fix for insideShop variable when purchasing a vehicle.
> Purchasing Vehicle Fix
